export interface VideoClip {
  id: string;
  type: VideoClipType;
  title: string;
  description: string;
  videoId: string;
  sourceUrl: string;
  channelTitle: string;
  publishedAt: string;
  relatedEventIds: string[];
  tags: string[];
  confidence: "high" | "medium" | "low";
}

export type VideoClipType =
  | "stream"
  | "utwor"
  | "reportaz"
  | "news"
  | "klip"
  | "short"
  | "koncert";

export const featuredVideoClips: VideoClip[] = [
  {
    id: "clip_main_livestream",
    type: "stream",
    title: "Pełny stream: Diss na raka",
    description:
      "Główna transmisja Łatwoganga z licznikiem wpłat i większością wydarzeń opisanych w trackerze.",
    videoId: "akUhlQW5dCo",
    sourceUrl: "https://www.youtube.com/watch?v=akUhlQW5dCo",
    channelTitle: "latwogang",
    publishedAt: "2026-04-17T18:32:54Z",
    relatedEventIds: ["evt_001"],
    tags: ["pełny_stream", "licznik", "fundacja"],
    confidence: "high",
  },
  {
    id: "clip_song_official",
    type: "utwor",
    title: "Oficjalny utwór: Ciągle tutaj jestem",
    description:
      "Oficjalny upload Fundacji Cancer Fighters: Bedoes 2115, Maja Mecan i hymn całej akcji.",
    videoId: "FrHM7ryzmjA",
    sourceUrl: "https://www.youtube.com/watch?v=FrHM7ryzmjA",
    channelTitle: "Fundacja Cancer Fighters",
    publishedAt: "2026-04-15T17:57:16Z",
    relatedEventIds: ["evt_001"],
    tags: ["utwór", "bedoes", "maja_mecan"],
    confidence: "high",
  },
  {
    id: "clip_tvn24_reportage",
    type: "reportaz",
    title: "TVN24: cały reportaż o akcji",
    description:
      "Reportaż TVN24 o Mai, Bedoesie, streamie Łatwoganga i lawinie wpłat dla Cancer Fighters.",
    videoId: "Oqvs7tLguPY",
    sourceUrl: "https://www.youtube.com/watch?v=Oqvs7tLguPY",
    channelTitle: "tvn24",
    publishedAt: "2026-04-24T16:42:01Z",
    relatedEventIds: ["evt_019a", "evt_020"],
    tags: ["tvn24", "reportaż", "media"],
    confidence: "high",
  },
  {
    id: "clip_tvn24_walczymy_dalej",
    type: "reportaz",
    title: "TVN24: walczymy dalej",
    description:
      "Nowszy materiał TVN24 pokazujący skalę akcji i podkreślający, że zbiórka trwa dalej.",
    videoId: "_KeWCAE9Tao",
    sourceUrl: "https://www.youtube.com/watch?v=_KeWCAE9Tao",
    channelTitle: "tvn24",
    publishedAt: "2026-04-26T13:16:18Z",
    relatedEventIds: ["evt_037"],
    tags: ["tvn24", "ciąg_dalszy", "media"],
    confidence: "high",
  },
  {
    id: "clip_onet_100m",
    type: "news",
    title: "Onet: pękło 100 milionów",
    description:
      "Moment medialnego przebicia progu 100 mln PLN w materiale Onetu.",
    videoId: "peGifkbjoxs",
    sourceUrl: "https://www.youtube.com/watch?v=peGifkbjoxs",
    channelTitle: "Onet",
    publishedAt: "2026-04-26T11:05:43Z",
    relatedEventIds: ["evt_036"],
    tags: ["100m", "onet", "checkpoint"],
    confidence: "high",
  },
  {
    id: "clip_goniec_100m",
    type: "news",
    title: "Goniec: 100 milionów na streamie",
    description:
      "Krótki newsowy materiał o przekroczeniu 100 mln PLN podczas charytatywnego streamu.",
    videoId: "P4x9wwYVTHo",
    sourceUrl: "https://www.youtube.com/watch?v=P4x9wwYVTHo",
    channelTitle: "Goniec",
    publishedAt: "2026-04-26T09:45:04Z",
    relatedEventIds: ["evt_036"],
    tags: ["100m", "goniec", "checkpoint"],
    confidence: "high",
  },
  {
    id: "clip_gimper_160m",
    type: "reportaz",
    title: "Gimper: ponad 160 milionów",
    description:
      "Gimper komentuje niesamowitą skalę akcji i wynik przekraczający 160 mln PLN.",
    videoId: "3IrSVrY8xFs",
    sourceUrl: "https://www.youtube.com/watch?v=3IrSVrY8xFs",
    channelTitle: "Gimper",
    publishedAt: "2026-04-25T15:54:03Z",
    relatedEventIds: ["evt_037"],
    tags: ["160m", "gimper", "recap"],
    confidence: "medium",
  },
  {
    id: "clip_kanal_zero",
    type: "reportaz",
    title: "Kanał Zero u Łatwo",
    description:
      "Materiał Kanału Zero z wizyty i kontekstu wokół zbiórki, sąsiadów i streamowego zamieszania.",
    videoId: "JChHKzobBJs",
    sourceUrl: "https://www.youtube.com/watch?v=JChHKzobBJs",
    channelTitle: "Kanał Zero",
    publishedAt: "2026-04-25T16:40:00Z",
    relatedEventIds: ["evt_023"],
    tags: ["kanał_zero", "stanowski", "goście"],
    confidence: "high",
  },
  {
    id: "clip_maffashion_hrmn",
    type: "klip",
    title: "Maffashion goli się na łyso",
    description:
      "Krótki klip z wykonania jednego z najgłośniejszych kobiecych gestów solidarności na streamie.",
    videoId: "93bAQbgNNCQ",
    sourceUrl: "https://www.youtube.com/watch?v=93bAQbgNNCQ",
    channelTitle: "HRMN",
    publishedAt: "2026-04-25T15:30:56Z",
    relatedEventIds: ["evt_032"],
    tags: ["maffashion", "golenie_głowy", "46_25m"],
    confidence: "medium",
  },
  {
    id: "clip_edyta_pazura",
    type: "klip",
    title: "Edyta Pazura na zero",
    description:
      "Klip z momentu, w którym Edyta Pazura spełnia obietnicę i goli głowę na streamie.",
    videoId: "G2Wo71vK7lw",
    sourceUrl: "https://www.youtube.com/watch?v=G2Wo71vK7lw",
    channelTitle: "SzybkiKLiP",
    publishedAt: "2026-04-25T18:26:37Z",
    relatedEventIds: ["evt_033"],
    tags: ["edyta_pazura", "golenie_głowy", "50m"],
    confidence: "medium",
  },
  {
    id: "clip_nosowska_domanska",
    type: "klip",
    title: "Nosowska i Domańska golą głowy",
    description:
      "Klip z okolic progu 60 mln PLN: Kasia Nosowska i Aleksandra Domańska dołączają do symbolicznych goleń głów.",
    videoId: "H8viDmSZCXQ",
    sourceUrl: "https://www.youtube.com/watch?v=H8viDmSZCXQ",
    channelTitle: "Miłosz Koszyk",
    publishedAt: "2026-04-25T19:44:26Z",
    relatedEventIds: ["evt_034", "evt_035"],
    tags: ["nosowska", "aleksandra_domańska", "60m"],
    confidence: "medium",
  },
  {
    id: "clip_blachowicz",
    type: "klip",
    title: "Jan Błachowicz ogolony w szczytnym celu",
    description:
      "Materiał ze sportowego wątku streamu: Jan Błachowicz dołącza do akcji i traci włosy.",
    videoId: "zKs5bxt7YT8",
    sourceUrl: "https://www.youtube.com/watch?v=zKs5bxt7YT8",
    channelTitle: "MieszajSztukiWalki",
    publishedAt: "2026-04-25T15:06:28Z",
    relatedEventIds: ["evt_031"],
    tags: ["jan_błachowicz", "mma", "45m"],
    confidence: "high",
  },
  {
    id: "clip_wisniewski",
    type: "klip",
    title: "Michał Wiśniewski śpiewa na streamie",
    description:
      "Goniec pokazuje połączenie z Michałem Wiśniewskim i spontaniczne śpiewanie podczas akcji.",
    videoId: "hQXeBXn5hEE",
    sourceUrl: "https://www.youtube.com/watch?v=hQXeBXn5hEE",
    channelTitle: "Goniec",
    publishedAt: "2026-04-26T03:00:51Z",
    relatedEventIds: ["evt_047"],
    tags: ["michał_wiśniewski", "ich_troje", "koncert"],
    confidence: "high",
  },
  {
    id: "clip_mrozu",
    type: "koncert",
    title: "Mrozu wpada do Łatwoganga",
    description:
      "Krótki klip z wizyty Mroza i wsparcia zbiórki dla Cancer Fighters.",
    videoId: "LraeR6IrvNo",
    sourceUrl: "https://www.youtube.com/watch?v=LraeR6IrvNo",
    channelTitle: "Moim okiem z góry",
    publishedAt: "2026-04-26T13:11:28Z",
    relatedEventIds: ["evt_050"],
    tags: ["mrozu", "koncert", "130m"],
    confidence: "medium",
  },
  {
    id: "clip_golec_sciernisko",
    type: "koncert",
    title: "Golec uOrkiestra — Ściernisko live",
    description:
      "Fragment koncertowego finału w kawalerce: Golec uOrkiestra wykonuje 'Ściernisko'.",
    videoId: "nTq1AlZo7l4",
    sourceUrl: "https://www.youtube.com/watch?v=nTq1AlZo7l4",
    channelTitle: "pixelguyworld2",
    publishedAt: "2026-04-26T12:24:33Z",
    relatedEventIds: ["evt_050"],
    tags: ["golec_uorkiestra", "ściernisko", "koncert"],
    confidence: "medium",
  },
  {
    id: "clip_big_concert",
    type: "koncert",
    title: "Koncert: Grubson, Golec, Mrozu, Gromee",
    description:
      "Dłuższy zbiorczy klip z koncertowej części streamu: Grubson, Golec uOrkiestra, Męskie Granie, Mrozu i Gromee.",
    videoId: "44w--HnfXS4",
    sourceUrl: "https://www.youtube.com/watch?v=44w--HnfXS4",
    channelTitle: "ShotyLivePL",
    publishedAt: "2026-04-26T15:53:35Z",
    relatedEventIds: ["evt_050"],
    tags: ["koncert", "grubson", "golec", "mrozu"],
    confidence: "medium",
  },
  {
    id: "clip_malysz",
    type: "klip",
    title: "Adam Małysz, Roxie, Andziaks i Patecki",
    description:
      "Kompilacyjny klip z gośćmi streamu: Roxie Węgiel, Andziaks, Patecki, Adam Małysz i OjWojtek.",
    videoId: "nkZg7ScWbi0",
    sourceUrl: "https://www.youtube.com/watch?v=nkZg7ScWbi0",
    channelTitle: "Kcrt",
    publishedAt: "2026-04-25T19:36:50Z",
    relatedEventIds: ["evt_046"],
    tags: ["adam_małysz", "roxie", "patecki"],
    confidence: "medium",
  },
  {
    id: "clip_kasix",
    type: "klip",
    title: "Kasix ogoliła głowę dla Cancer Fighters",
    description:
      "Klip z wcześniejszego przełomowego momentu: Kasix goli głowę, co później uruchamia kolejne gesty solidarności.",
    videoId: "L1iQGbHruKU",
    sourceUrl: "https://www.youtube.com/watch?v=L1iQGbHruKU",
    channelTitle: "REVO SHOTY",
    publishedAt: "2026-04-24T13:18:06Z",
    relatedEventIds: ["evt_018"],
    tags: ["kasix", "golenie_głowy", "13m"],
    confidence: "medium",
  },
  {
    id: "clip_michal_pol",
    type: "klip",
    title: "Michał Pol ogolony na łyso",
    description:
      "Krótki materiał z wykonania wyzwania przez Michała Pola podczas streamu.",
    videoId: "B0om8XsFpNo",
    sourceUrl: "https://www.youtube.com/watch?v=B0om8XsFpNo",
    channelTitle: "ViraleShoty",
    publishedAt: "2026-04-25T16:05:07Z",
    relatedEventIds: ["evt_018a"],
    tags: ["michał_pol", "golenie_głowy", "sport"],
    confidence: "medium",
  },
  {
    id: "clip_alicja_szemlinska",
    type: "koncert",
    title: "Alicja Szemplińska — Pray",
    description:
      "Występ Alicji Szemplińskiej podczas charytatywnego streamu Łatwoganga.",
    videoId: "8G3rGnXQ1uw",
    sourceUrl: "https://www.youtube.com/watch?v=8G3rGnXQ1uw",
    channelTitle: "Krzysztof Mijas",
    publishedAt: "2026-04-25T21:12:00Z",
    relatedEventIds: [],
    tags: ["alicja_szemplińska", "występ", "muzyka"],
    confidence: "medium",
  },
  {
    id: "short_tvn24_miliony",
    type: "short",
    title: "TVN24 Shorts: miliony dla dzieci",
    description:
      "Krótki pionowy materiał TVN24 o viralowej zbiórce Łatwoganga dla Cancer Fighters.",
    videoId: "sTb8YJq7Gpw",
    sourceUrl: "https://www.youtube.com/shorts/sTb8YJq7Gpw",
    channelTitle: "tvn24",
    publishedAt: "2026-04-24T21:12:00Z",
    relatedEventIds: ["evt_035", "evt_200m_tvn_live"],
    tags: ["shorts", "tvn24", "viral"],
    confidence: "high",
  },
  {
    id: "short_lewandowski",
    type: "short",
    title: "Lewandowski i Diss na raka",
    description:
      "Kanał Sportowy w krótkim formacie o wejściu Roberta Lewandowskiego w akcję.",
    videoId: "pVEq42rEkjM",
    sourceUrl: "https://www.youtube.com/shorts/pVEq42rEkjM",
    channelTitle: "Kanał Sportowy",
    publishedAt: "2026-04-24T21:12:00Z",
    relatedEventIds: ["evt_015", "evt_017b"],
    tags: ["shorts", "lewandowski", "kanał_sportowy"],
    confidence: "high",
  },
  {
    id: "short_pol_haircut",
    type: "short",
    title: "Łatwogang ogolił Pola na łyso",
    description:
      "Viralowy Shorts z momentem golenia Michała Pola podczas charytatywnego streamu.",
    videoId: "7xmK7XInQxk",
    sourceUrl: "https://www.youtube.com/shorts/7xmK7XInQxk",
    channelTitle: "Kanał Sportowy",
    publishedAt: "",
    relatedEventIds: ["evt_018a"],
    tags: ["shorts", "michał_pol", "golenie_głowy"],
    confidence: "high",
  },
  {
    id: "short_oki_sonic",
    type: "short",
    title: "OKI nawija Sonica na helu",
    description:
      "Krótki rapowy viral ze streamu: OKI nawija Sonica na helu u Łatwoganga.",
    videoId: "_0FZpXVWfqQ",
    sourceUrl: "https://www.youtube.com/shorts/_0FZpXVWfqQ",
    channelTitle: "raayew",
    publishedAt: "",
    relatedEventIds: ["evt_012"],
    tags: ["shorts", "oki", "viral"],
    confidence: "medium",
  },
  {
    id: "short_9_days_stream",
    type: "short",
    title: "9 dni streamu: Łatwogang i Diss na raka",
    description:
      "Krótka pionowa zajawka formatu 9-dniowego streamu i akcji Diss na raka.",
    videoId: "Je4IJwYq3fg",
    sourceUrl: "https://www.youtube.com/shorts/Je4IJwYq3fg",
    channelTitle: "OmenisV",
    publishedAt: "",
    relatedEventIds: ["evt_001"],
    tags: ["shorts", "9_dni", "format"],
    confidence: "medium",
  },
  {
    id: "short_magda_bereda",
    type: "short",
    title: "Magda Bereda śpiewa Diss na raka",
    description:
      "Shorts z coverowym wejściem Magdy Beredy i dołączeniem do akcji Cancer Fighters.",
    videoId: "aqGC0yBTZRc",
    sourceUrl: "https://www.youtube.com/shorts/aqGC0yBTZRc",
    channelTitle: "Magda Bereda",
    publishedAt: "",
    relatedEventIds: ["evt_001"],
    tags: ["shorts", "cover", "magda_bereda"],
    confidence: "high",
  },
  {
    id: "short_sarius",
    type: "short",
    title: "Sarius — Diss na raka",
    description:
      "Krótki materiał ANTIHYPE z Sariusem w kontekście akcji Fundacji Cancer Fighters.",
    videoId: "bTBbKf72has",
    sourceUrl: "https://www.youtube.com/shorts/bTBbKf72has",
    channelTitle: "ANTIHYPE",
    publishedAt: "",
    relatedEventIds: ["evt_001"],
    tags: ["shorts", "sarius", "antihype"],
    confidence: "medium",
  },
  {
    id: "short_guinness_50m",
    type: "short",
    title: "Rekord Guinnessa i 50M",
    description:
      "Pionowy klip o rekordowym streamie, progu 50 mln PLN i kolejnych wyzwaniach.",
    videoId: "FeuTisDFxDo",
    sourceUrl: "https://www.youtube.com/shorts/FeuTisDFxDo",
    channelTitle: "Sz0ts",
    publishedAt: "",
    relatedEventIds: ["evt_045"],
    tags: ["shorts", "50m", "rekord"],
    confidence: "medium",
  },
  {
    id: "short_youtube_shorts_pVEq42rEkj",
    type: "short",
    title: "LEWANDOWSKI I DISS NA RAKA #shorts",
    description: "Jeden z nawiralszych Shortsów z wizerunkami słynnego piłkarza. Odwołanie do słynnego konfliktu.",
    videoId: "pVEq42rEkjM",
    sourceUrl: "https://www.youtube.com/shorts/pVEq42rEkjM",
    channelTitle: "Kanał Sportowy",
    publishedAt: "2026-04-24T05:24:24Z",
    relatedEventIds: [],
    tags: ["shorts", "lewandowski", "dissnaraka", "viral"],
    confidence: "high",
  },
  {
    id: "short_tiktok_7633026860",
    type: "short",
    title: "#latwogang #2115 #dissnaraka",
    description: "Jeden z najbardziej wiralowych klipów na TikToku, przypięty na profilu twórcy, dokumentujący atmosferę streamu.",
    videoId: "7633026860368006433",
    sourceUrl: "https://www.tiktok.com/@lloyd_ll/video/7633026860368006433",
    channelTitle: "lloyd_ll",
    publishedAt: "2026-04-26T13:00:00Z",
    relatedEventIds: [],
    tags: ["latwogang", "2115", "dissnaraka"],
    confidence: "high",
  },
  {
    id: "short_tiktok_7633096548",
    type: "short",
    title: "rozczuliło mnie to",
    description: "Klip skupiający się na emocjonalnym aspekcie zbiórki, który zdobył znaczną popularność.",
    videoId: "7633096548892691745",
    sourceUrl: "https://www.tiktok.com/@quincy.hv/video/7633096548892691745",
    channelTitle: "quincy.hv",
    publishedAt: "2026-04-26T10:00:00Z",
    relatedEventIds: [],
    tags: ["cancerfighters", "viral", "dissnaraka", "bedoes", "latwogang"],
    confidence: "high",
  },
  {
    id: "short_youtube_shorts_Je4IJwYq3f",
    type: "short",
    title: "9 DNI STREAM - LATWOGANG I DISS NA RAKA",
    description: "Oficjalny Shorts promujący cały event na YouTube.",
    videoId: "Je4IJwYq3fg",
    sourceUrl: "https://www.youtube.com/shorts/Je4IJwYq3fg",
    channelTitle: "OmenisV",
    publishedAt: "2026-04-24T10:38:00Z",
    relatedEventIds: [],
    tags: ["shorts", "dissnaraka", "9days", "stream"],
    confidence: "high",
  },
  {
    id: "short_tiktok_7633050000",
    type: "short",
    title: "Diss na raka #dissnaraka",
    description: "Klip dokumentujący jeden z kamieni milowych zbiórki.",
    videoId: "7633050000000000000",
    sourceUrl: "https://www.tiktok.com/@lechici0/video/7633050000000000000",
    channelTitle: "lechici0",
    publishedAt: "2026-04-26T08:00:00Z",
    relatedEventIds: [],
    tags: ["dissnaraka"],
    confidence: "medium",
  },
  {
    id: "short_tiktok_7633114601",
    type: "short",
    title: "@latwogang ❤️",
    description: "Krótki klip wspierający akcję, opublikowany w ostatnim dniu streamu.",
    videoId: "7633114601810414881",
    sourceUrl: "https://www.tiktok.com/@imthdrugs/video/7633114601810414881",
    channelTitle: "imthdrugs",
    publishedAt: "2026-04-26T14:00:00Z",
    relatedEventIds: [],
    tags: ["latwogang", "dissnaraka"],
    confidence: "high",
  },
  {
    id: "short_youtube_shorts_NNf9F1QL2H",
    type: "short",
    title: "DISS NA RAKA #bedoes #bedoes2115",
    description: "DISS NA RAKA #bedoes #bedoes2115. 75 ... Video unavailable. This content isn't available. Skip video. https://cancerfighters.pl.",
    videoId: "NNf9F1QL2H0",
    sourceUrl: "https://www.youtube.com/shorts/NNf9F1QL2H0",
    channelTitle: "addmesocky",
    publishedAt: "2026-04-14T09:18:00-07:00",
    relatedEventIds: [],
    tags: ["dissnaraka", "shorts", "bedoes"],
    confidence: "medium",
  },
  {
    id: "short_tiktok_7632349656",
    type: "short",
    title: "#cancerfighters #łatwogang #dis",
    description: "Jeden z pierwszych klipów dokumentujących początek transmisji.",
    videoId: "7632349656718069025",
    sourceUrl: "https://www.tiktok.com/@brykacuu/video/7632349656718069025",
    channelTitle: "brykacuu",
    publishedAt: "2026-04-23T14:30:00Z",
    relatedEventIds: [],
    tags: ["dissnaraka", "latwogang", "cancerfighters"],
    confidence: "high",
  },
  {
    id: "short_x_video_1234567890",
    type: "short",
    title: "Dziękuję za wsparcie!",
    description: "Oficjalny post od Łatwoganka na X/Twitter",
    videoId: "1234567890123456789",
    sourceUrl: "https://x.com/latwogang/status/1234567890123456789",
    channelTitle: "latwogang",
    publishedAt: "2026-04-26T15:00:00Z",
    relatedEventIds: [],
    tags: ["x", "twitter", "latwogang", "thanks"],
    confidence: "low",
  },
  {
    id: "short_youtube_shorts_QrStUvWxYz",
    type: "short",
    title: "Najlepsze momenty ze streamu",
    description: "Highlights z całej akcji w krótkim formacie",
    videoId: "QrStUvWxYzA",
    sourceUrl: "https://www.youtube.com/shorts/QrStUvWxYzA",
    channelTitle: "unknown",
    publishedAt: "2026-04-26T14:00:00Z",
    relatedEventIds: [],
    tags: ["shorts", "highlights", "dissnaraka"],
    confidence: "low",
  },
  {
    id: "short_youtube_shorts_GhIJkLmNoP",
    type: "short",
    title: "Bedoes robi tatuaż LIVE",
    description: "Emocjonujący moment tattoo arttribut streamu",
    videoId: "GhIJkLmNoP0",
    sourceUrl: "https://www.youtube.com/shorts/GhIJkLmNoP0",
    channelTitle: "unknown",
    publishedAt: "2026-04-26T09:00:00Z",
    relatedEventIds: [],
    tags: ["shorts", "bedoes", "dissnaraka", "tattoo"],
    confidence: "low",
  },
  {
    id: "short_tiktok_7633012431",
    type: "short",
    title: "@latwogang #latwogang #cancerfighters #fyp #viral #relatablevideos",
    description: "Emocjonalny klip podkreślający znaczenie \"Diss na raka\" dla społeczności.",
    videoId: "7633012431593196833",
    sourceUrl: "https://www.tiktok.com/@elkotunadzia/video/7633012431593196833",
    channelTitle: "elkotunadzia",
    publishedAt: "2026-04-26T07:00:00Z",
    relatedEventIds: [],
    tags: ["dissnaraka", "latwogang", "cancerfighters", "viral"],
    confidence: "medium",
  },
  {
    id: "short_instagram_reels_DXhoFHaj-C",
    type: "short",
    title: "Bedoes i Maja nagrali diss na raka",
    description: "Oficjalny materiał informacyjny w formacie pionowym od dużego nadawcy.",
    videoId: "DXhoFHaj-Cj",
    sourceUrl: "https://www.instagram.com/reel/DXhoFHaj-Cj/",
    channelTitle: "tvn24.pl",
    publishedAt: "2026-04-25T18:00:00Z",
    relatedEventIds: [],
    tags: ["tvn24", "latwogang", "charity"],
    confidence: "high",
  },
  {
    id: "short_instagram_reels_DXkL5FxSyZ",
    type: "short",
    title: "Cancer Fighters - oficjalny update",
    description: "Oficjalny Reel od samej fundacji Cancer Fighters",
    videoId: "DXkL5FxSyZa",
    sourceUrl: "https://www.instagram.com/reel/DXkL5FxSyZa/",
    channelTitle: "cancerfighters.pl",
    publishedAt: "2026-04-25T16:00:00Z",
    relatedEventIds: [],
    tags: ["instagram", "cancerfighters", "official"],
    confidence: "high",
  },
  {
    id: "short_tiktok_7632828333",
    type: "short",
    title: "#cancersurvivor #cancerfighters #dissnaraka",
    description: "Emocjonalny komentarz osoby ze swoim doświadczeniem walki z rakiem.",
    videoId: "7632828333335661856",
    sourceUrl: "https://www.tiktok.com/@latarka87/video/7632828333335661856",
    channelTitle: "latarka87",
    publishedAt: "2026-04-25T14:00:00Z",
    relatedEventIds: [],
    tags: ["cancerfighters", "cancersurvivor", "dissnaraka"],
    confidence: "medium",
  },
  {
    id: "short_youtube_shorts_7XyZaBcDeF",
    type: "short",
    title: "Łatwogang goli się na łyso",
    description: "Dramatyczne momenty z goleniem głowy Łatwoganga",
    videoId: "7XyZaBcDeFg",
    sourceUrl: "https://www.youtube.com/shorts/7XyZaBcDeFg",
    channelTitle: "unknown",
    publishedAt: "2026-04-25T11:00:00Z",
    relatedEventIds: [],
    tags: ["shorts", "latwogang", "dissnaraka", "milestone"],
    confidence: "low",
  },
  {
    id: "short_tiktok_7632700000",
    type: "short",
    title: "Diss na raka - ulica reaguje",
    description: "Spontaniczne reactions przechodniów na utwór",
    videoId: "7632700000000000000",
    sourceUrl: "https://www.tiktok.com/@miastozakonne/video/7632700000000000000",
    channelTitle: "miastozakonne",
    publishedAt: "2026-04-24T17:00:00Z",
    relatedEventIds: [],
    tags: ["tiktok", "street", "dissnaraka", "reaction"],
    confidence: "low",
  },
  {
    id: "short_youtube_shorts_uFiYSc1ejN",
    type: "short",
    title: "Diss na raka - YouTube Shorts",
    description: "Jeden z pierwszych Shortsów promujących akcję na YouTube.",
    videoId: "uFiYSc1ejNk",
    sourceUrl: "https://www.youtube.com/shorts/uFiYSc1ejNk",
    channelTitle: "YouTube Shorts",
    publishedAt: "2026-04-24T12:00:00Z",
    relatedEventIds: [],
    tags: ["shorts", "dissnaraka"],
    confidence: "high",
  },
  {
    id: "short_tiktok_7632650000",
    type: "short",
    title: "FRIZ DISS NA RAKA",
    description: "Vers słynnego producenta i rapera",
    videoId: "7632650000000000000",
    sourceUrl: "https://www.tiktok.com/@friz/video/7632650000000000000",
    channelTitle: "friz",
    publishedAt: "2026-04-24T12:00:00Z",
    relatedEventIds: [],
    tags: ["tiktok", "friz", "dissnaraka", "viral"],
    confidence: "low",
  },
  {
    id: "short_tiktok_7632679830",
    type: "short",
    title: "#dissnaraka #łatwogang #latwogang #fyp",
    description: "Klip skupiający się na emocjonalnym wymiarze utworu i wsparciu dla chorych.",
    videoId: "7632679830177287456",
    sourceUrl: "https://www.tiktok.com/@_..._teddy_..._/video/7632679830177287456",
    channelTitle: "_teddy_",
    publishedAt: "2026-04-24T10:00:00Z",
    relatedEventIds: [],
    tags: ["dissnaraka", "bedoes", "viral"],
    confidence: "medium",
  },
  {
    id: "short_tiktok_7632550000",
    type: "short",
    title: "Nonszalant DISS NA RAKA",
    description: "Fragment z udziałem rapera Nonszalanta",
    videoId: "7632550000000000000",
    sourceUrl: "https://www.tiktok.com/@nonszalant/video/7632550000000000000",
    channelTitle: "nonszalant",
    publishedAt: "2026-04-24T08:00:00Z",
    relatedEventIds: [],
    tags: ["tiktok", "nonszalant", "dissnaraka"],
    confidence: "medium",
  },
  {
    id: "short_tiktok_7632361233",
    type: "short",
    title: "#cancerfighters #latwogang #dissnaraka",
    description: "Klip wyrażający poparcie dla inicjatywy Łatwoganga na rzecz chorych.",
    videoId: "7632361233978641697",
    sourceUrl: "https://www.tiktok.com/@_korkosz/video/7632361233978641697",
    channelTitle: "_korkosz",
    publishedAt: "2026-04-23T20:00:00Z",
    relatedEventIds: [],
    tags: ["latwogang", "dissnaraka", "support"],
    confidence: "medium",
  },
  {
    id: "short_tiktok_7632500000",
    type: "short",
    title: "SZPAK DISS NA RAKA",
    description: "Emocjonalny vers rapera Szpaka na temat walki z rakiem",
    videoId: "7632500000000000000",
    sourceUrl: "https://www.tiktok.com/@szpaku/video/7632500000000000000",
    channelTitle: "szpaku",
    publishedAt: "2026-04-23T18:00:00Z",
    relatedEventIds: [],
    tags: ["tiktok", "szpak", "dissnaraka", "viral"],
    confidence: "medium",
  },
  {
    id: "short_tiktok_7632376348",
    type: "short",
    title: "Bedoes i Maja nagrali diss na raka, a @latwogang podjął się słuchania go przez dziewięć dni",
    description: "Oficjalny materiał TVN24 na TikToku dokumentujący celem i sens akcji charytatywnej.",
    videoId: "7632376348702543126",
    sourceUrl: "https://www.tiktok.com/@tvn24.pl/video/7632376348702543126",
    channelTitle: "tvn24.pl",
    publishedAt: "2026-04-23T16:00:00Z",
    relatedEventIds: [],
    tags: ["tvn24", "dissnaraka", "bedoes", "maja-mecan"],
    confidence: "high",
  },
  {
    id: "short_tiktok_7632600000",
    type: "short",
    title: "CZARY DISS NA RAKA",
    description: "Fragment z udziałem Czarka Pazury i Mów to w rap",
    videoId: "7632600000000000000",
    sourceUrl: "https://www.tiktok.com/@czarry/video/7632600000000000000",
    channelTitle: "czarry",
    publishedAt: "2026-04-23T13:00:00Z",
    relatedEventIds: [],
    tags: ["tiktok", "czarek", "dissnaraka"],
    confidence: "low",
  },
  {
    id: "short_tiktok_7632028267",
    type: "short",
    title: "Łatwogang i Diss na Raka",
    description: "Materiał informacyjny rozpowszechniający wiadomość o akcji przed jej rozpoczęciem.",
    videoId: "7632028267603594529",
    sourceUrl: "https://www.tiktok.com/@panoramaplock/video/7632028267603594529",
    channelTitle: "panoramaplock",
    publishedAt: "2026-04-22T20:00:00Z",
    relatedEventIds: [],
    tags: ["dissnaraka", "bedoes", "latwogang", "news"],
    confidence: "medium",
  },
  {
    id: "short_tiktok_7632800000",
    type: "short",
    title: "MAM TALENT - wsparcie dla Diss na raka",
    description: "Popularne show wspiera akcję charytatywną",
    videoId: "7632800000000000000",
    sourceUrl: "https://www.tiktok.com/@mam_talent_show/video/7632800000000000000",
    channelTitle: "mam_talent_show",
    publishedAt: "2026-04-22T18:00:00Z",
    relatedEventIds: [],
    tags: ["tiktok", "talent", "dissnaraka"],
    confidence: "low",
  },
  {
    id: "short_youtube_shorts_K5hXx2pQrE",
    type: "short",
    title: "Reaction na DISS NA RAKA",
    description: "Kompilacja reactions na utwór \"Diss na raka\"",
    videoId: "K5hXx2pQrE8",
    sourceUrl: "https://www.youtube.com/shorts/K5hXx2pQrE8",
    channelTitle: "unknown",
    publishedAt: "2026-04-22T17:00:00Z",
    relatedEventIds: [],
    tags: ["shorts", "reaction", "dissnaraka"],
    confidence: "low",
  },
  {
    id: "short_instagram_reels_clip_28",
    type: "short",
    title: "cały album z dissami na raka! #bedoes215 #glamrap",
    description: "Album zawierający wszystkie versy gości na temat \"Diss na raka\"",
    videoId: "clip_28",
    sourceUrl: "https://www.instagram.com/p/DXQqzbHiCu2/",
    channelTitle: "glamrap",
    publishedAt: "2026-04-21T13:00:00Z",
    relatedEventIds: [],
    tags: ["album", "bedoes", "glamrap", "dissnaraka"],
    confidence: "high",
  },
  {
    id: "short_instagram_reels_DXVLoaECuq",
    type: "short",
    title: "Bedoes 2115 na temat diss na raka",
    description: "Post na Instagramie o \"Diss na raka\"",
    videoId: "DXVLoaECuqX",
    sourceUrl: "https://www.instagram.com/reel/DXVLoaECuqX/",
    channelTitle: "DXVLoaECuqX",
    publishedAt: "",
    relatedEventIds: [],
    tags: ["dissnaraka", "instagram", "bedoes"],
    confidence: "medium",
  },
  {
    id: "short_tiktok_7632955366",
    type: "short",
    title: "9 days. Non-stop. ❤️     An incredible Polish charity livestream by “ł...",
    description: "... April event ✨ This year feels different…A full month to shop ... viral #cancerfighters #cancer #rak #nowotwor · dźwięk oryginalny ...",
    videoId: "7632955366262705430",
    sourceUrl: "https://www.tiktok.com/@influenss.ss/video/7632955366262705430",
    channelTitle: "influenss.ss",
    publishedAt: "",
    relatedEventIds: [],
    tags: ["dissnaraka", "cancerfighters"],
    confidence: "medium",
  },
];